name: TEST CASES
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 11.x
    - run: npm install
    - run: npm test
      env:
        QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
        QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
        QINIU_TEST_BUCKET: ${{ secrets.QINIU_TEST_BUCKET }}
        QINIU_TEST_BUCKET_REGION_ID: ${{ secrets.QINIU_TEST_BUCKET_REGION_ID }}
